Add BODs 22-01 and 23-02 to CyHy Notification Body
jsf9k/cyhy-mailer pull request #98
Opened 2023-08-04 04:04 UTC by climber-girl

## 🗣 Description ##

As part of the BOD 23-02 updates, we want to update the body of the CyHy notifications emails to include mention of networked management interfaces with the context of the potentially risky services we flag. This update also includes updating the link for 19-02 and adding 22-01 since we forgot to include that language when adding KEVs to the notifications.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] *All* future TODOs are captured in issues, which are referenced
      in code comments.
- [ ] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [ ] Tests have been added and/or modified to cover the changes in this PR.
- [ ] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Revert dependencies to default branches.
- [ ] Finalize version.

## ✅ Post-merge checklist ##

- [ ] Create a release.

2023-08-10 13:27 UTC, dav3r requested changes
Sorry it took me a bit to review this.  Please take a look at the small items I noted.  Feel free to take or leave the minor wording suggestions, but the smart quotes need to be removed for sure.

2023-08-10 13:27 UTC, dav3r commented on cyhy/mailer/CyhyNotificationMessage.py
>  Cyber Hygiene scans of your host(s) conducted in the past day have detected one or both of the following:
With how the wording here has grown, I think this sounds better, don't you?
```suggestion
Cyber Hygiene scans of your host(s) conducted in the past day have detected one or more of the following:
```

2023-08-10 13:27 UTC, dav3r commented on cyhy/mailer/CyhyNotificationMessage.py
> +{{#is_federal}}As part of BOD 22-01, any “known exploited” findings, regardless of severity, need to be remediated within two weeks.{{/is_federal}}{{^is_federal}}CISA recommends remediating known exp
Replace smart quotes with regular quotes:
```suggestion
{{#is_federal}}As part of BOD 22-01, any "known exploited" findings, regardless of severity, need to be remediated within two weeks.{{/is_federal}}{{^is_federal}}CISA recommends remediating known exploited vulnerabilities, regardless of severity, within two weeks.{{/is_federal}}
```

2023-08-10 13:27 UTC, dav3r commented on cyhy/mailer/CyhyNotificationMessage.py
>  <p>Cyber Hygiene scans of your host(s) conducted in the past day have detected one or both of the following:
Mirroring my earlier suggestion:
```suggestion
<p>Cyber Hygiene scans of your host(s) conducted in the past day have detected one or more of the following:
```

2023-08-10 13:27 UTC, dav3r commented on cyhy/mailer/CyhyNotificationMessage.py
> +<p>{{#is_federal}}As part of <a href="https://www.cisa.gov/news-events/directives/bod-22-01-reducing-significant-risk-known-exploited-vulnerabilities">BOD 22-01</a>, any “known exploited” findings, r
Replace smart quotes with regular quotes:
```suggestion
<p>{{#is_federal}}As part of <a href="https://www.cisa.gov/news-events/directives/bod-22-01-reducing-significant-risk-known-exploited-vulnerabilities">BOD 22-01</a>, any "known exploited" findings, regardless of severity, need to be remediated within two weeks.{{/is_federal}}{{^is_federal}}CISA recommends remediating known exploited vulnerabilities, regardless of severity, within two weeks.{{/is_federal}}</p>
```

2023-08-10 19:08 UTC, KeithBonesJr commented on cyhy/mailer/CyhyNotificationMessage.py
> +<p>{{#is_federal}}As part of <a href="https://www.cisa.gov/news-events/directives/bod-22-01-reducing-significant-risk-known-exploited-vulnerabilities">BOD 22-01</a>, any “known exploited” findings, r
Looks great!

2023-08-10 20:02 UTC, dv4harr10 commented on cyhy/mailer/CyhyNotificationMessage.py
> +{{#is_federal}}As part of BOD 22-01, any “known exploited” findings, regardless of severity, need to be remediated within two weeks.{{/is_federal}}{{^is_federal}}CISA recommends remediating known exp
Hi Team, climber-girl CODEOWNERS file contains errors @ https://github.com/climber-girl/cyhy-mailer/blob/climber-girl-patch-1/.github/CODEOWNERS

2023-08-11 07:49 UTC, mcdonnnj commented on cyhy/mailer/CyhyNotificationMessage.py
> +{{#is_federal}}As part of BOD 22-01, any “known exploited” findings, regardless of severity, need to be remediated within two weeks.{{/is_federal}}{{^is_federal}}CISA recommends remediating known exp
@dv4harr10 Yes because we do not have write permission for the forked repository. We can ignore this because we _do_ have write permission for _this_, the target repository.

2023-08-11 15:45 UTC, dav3r approved these changes
Looks great to me! 👍

2023-08-11 16:27 UTC, mcdonnnj approved these changes
This all looks pretty good to me. I have a couple of items of feedback for consideration however.

2023-08-11 16:27 UTC, mcdonnnj commented on cyhy/mailer/CyhyNotificationMessage.py
> +CISA also recommends reviewing hosts with potentially risky open services (e.g. RDP, Telnet, etc.), especially if they are functioning as networked management interfaces, to ensure that each service
I know this is technically already committed language but `the service is up-to-date on the latest version` sounds repetitive as if it's up-to-date it's on the latest version.

2023-08-11 16:27 UTC, mcdonnnj commented on cyhy/mailer/CyhyNotificationMessage.py
> +{{#is_federal}}As part of BOD 23-02, networked management interfaces exposed to the public internet must either be shut off or protected by capabilities that enforce access control to the interface t
Saying "shut off" feels ambiguous here. Are we just talking removing public visibility or what? The BOD specifies removing it from the internet.

2023-08-11 16:27 UTC, mcdonnnj commented on cyhy/mailer/CyhyNotificationMessage.py
> +<p>CISA also recommends reviewing hosts with potentially risky open services (e.g. RDP, Telnet, etc.), <em>especially if they are functioning as networked management interfaces</em>, to ensure that e
Just for consistency the same comment about `the service is up-to-date on the latest version`.

2023-08-11 16:27 UTC, mcdonnnj commented on cyhy/mailer/CyhyNotificationMessage.py
> +<p>{{#is_federal}}As part of <a href="https://www.cisa.gov/news-events/directives/binding-operational-directive-23-02">BOD 23-02</a>, networked management interfaces exposed to the public internet mu
Just for consistency the same comment about "shut off".

2023-08-11 17:00 UTC, dav3r commented on cyhy/mailer/CyhyNotificationMessage.py
> +CISA also recommends reviewing hosts with potentially risky open services (e.g. RDP, Telnet, etc.), especially if they are functioning as networked management interfaces, to ensure that each service
I think the "on the latest version" clause ensures that people understand exactly what is meant by "up-to-date".

@climber-girl or @KeithBonesJr - can you please weigh in here so that we can get this resolved?

2023-08-11 17:01 UTC, dav3r commented on cyhy/mailer/CyhyNotificationMessage.py
> +{{#is_federal}}As part of BOD 23-02, networked management interfaces exposed to the public internet must either be shut off or protected by capabilities that enforce access control to the interface t
@climber-girl or @KeithBonesJr - can you please weigh in here so that we can get this resolved?

2023-08-11 17:05 UTC, mcdonnnj commented on cyhy/mailer/CyhyNotificationMessage.py
> +CISA also recommends reviewing hosts with potentially risky open services (e.g. RDP, Telnet, etc.), especially if they are functioning as networked management interfaces, to ensure that each service
I guess part of what I'm getting at is if you need to specify "on the latest version" then is up-to-date necessary. Would it just be simpler as `the service is on the latest version`.

2023-08-11 17:07 UTC, climber-girl commented on cyhy/mailer/CyhyNotificationMessage.py
>  Cyber Hygiene scans of your host(s) conducted in the past day have detected one or both of the following:
Makes sense to me! :)

2023-08-11 17:07 UTC, climber-girl commented on cyhy/mailer/CyhyNotificationMessage.py
>  <p>Cyber Hygiene scans of your host(s) conducted in the past day have detected one or both of the following:
All good here :)

2023-08-11 17:09 UTC, climber-girl commented on cyhy/mailer/CyhyNotificationMessage.py
> +CISA also recommends reviewing hosts with potentially risky open services (e.g. RDP, Telnet, etc.), especially if they are functioning as networked management interfaces, to ensure that each service
I'm fine with cutting out "on the latest version"

2023-08-11 17:13 UTC, climber-girl commented on cyhy/mailer/CyhyNotificationMessage.py
> +{{#is_federal}}As part of BOD 23-02, networked management interfaces exposed to the public internet must either be shut off or protected by capabilities that enforce access control to the interface t
We can replace "shut off" with "removed from the internet by making it only accessible from an internal enterprise network"

2023-08-11 17:14 UTC, climber-girl commented on cyhy/mailer/CyhyNotificationMessage.py
> +<p>CISA also recommends reviewing hosts with potentially risky open services (e.g. RDP, Telnet, etc.), <em>especially if they are functioning as networked management interfaces</em>, to ensure that e
See comment on related conversation :)

2023-08-11 17:14 UTC, climber-girl commented on cyhy/mailer/CyhyNotificationMessage.py
> +<p>{{#is_federal}}As part of <a href="https://www.cisa.gov/news-events/directives/binding-operational-directive-23-02">BOD 23-02</a>, networked management interfaces exposed to the public internet mu
See comment on related conversation :)

2023-08-11 17:24 UTC, dav3r commented on cyhy/mailer/CyhyNotificationMessage.py
> +<p>{{#is_federal}}As part of <a href="https://www.cisa.gov/news-events/directives/binding-operational-directive-23-02">BOD 23-02</a>, networked management interfaces exposed to the public internet mu
Please see https://github.com/cisagov/cyhy-mailer/pull/98/commits/7608ffcb687913c7acb090292f38629b437c59aa.

2023-08-11 17:24 UTC, dav3r commented on cyhy/mailer/CyhyNotificationMessage.py
> +<p>CISA also recommends reviewing hosts with potentially risky open services (e.g. RDP, Telnet, etc.), <em>especially if they are functioning as networked management interfaces</em>, to ensure that e
Please see https://github.com/cisagov/cyhy-mailer/pull/98/commits/7608ffcb687913c7acb090292f38629b437c59aa.

2023-08-11 17:24 UTC, dav3r commented on cyhy/mailer/CyhyNotificationMessage.py
> +{{#is_federal}}As part of BOD 23-02, networked management interfaces exposed to the public internet must either be shut off or protected by capabilities that enforce access control to the interface t
Please see https://github.com/cisagov/cyhy-mailer/pull/98/commits/7608ffcb687913c7acb090292f38629b437c59aa.

2023-08-11 17:25 UTC, dav3r commented on cyhy/mailer/CyhyNotificationMessage.py
> +CISA also recommends reviewing hosts with potentially risky open services (e.g. RDP, Telnet, etc.), especially if they are functioning as networked management interfaces, to ensure that each service
Please see https://github.com/cisagov/cyhy-mailer/pull/98/commits/7608ffcb687913c7acb090292f38629b437c59aa.

2023-08-11 18:11 UTC, merged